spring:
  data:
    cassandra:
      keyspace-name: mykeyspace
      contact-points: localhost
      port: 9042
      schemaAction: CREATE_IF_NOT_EXISTS
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
      locaDatacenter: datacenter1